RawMaterials = Object.freeze({
    None: 0,
    ResistanceToVirus: 1,
    EvolutionPoints: 2,
    PaperTowels: 3,
    AntibacterialWipe: 4,
    DisinfectantLiquid: 5,
    RubberGloves: 6,
    TabletsForImmunity: 7,
    CottonMask: 8,
    CourierDeliveringFoodToHomes: 9,
    Thermometer: 10,
    Antipyretics: 11,
    MaskWithFilter: 12,
    OxygenBottle: 13,
    ProtectiveSuit: 14,
    Volunteers: 15,
    MedicalUniversityStudents: 16,
    InternalMedicineDoctors: 17,
    Clinic: 18,
    FreePreliminaryTestsForSuspects: 19,
    DisinfectingRooms: 20,
    Ambulances: 21,
    Nurses: 22,
    Hospitals: 23,
    SanitaryInspections: 24,
    SpecialistDoctors: 25,
    SecondDegreeSpecialists: 26,
    PromotingHygiene: 27,
    TemperatureMeasurementsAndPreliminaryInterview: 28,
    ForcedObservationOfSuspects: 29,
    IncreasedFlightControl: 30,
    IncreasedControlOfInternationalTransport: 31,
    EnhancedBorderControl: 32,
    RestrictingMassEvents: 33,
    RestrictingAccessToCulturalGoods: 34,
    IncreasedSecurityProceduresForSchools: 35,
    PromotionOfRemoteWork: 36,
    AdditionalVacationDays: 37,
    AllocationOfFoodAndSanitaryProducts: 38,
    PromotionOfCremationOfCorpses: 39,
    Biologists: 40,
    CollectingSamples: 41,
    Scientists: 42,
    VirusTesting: 43,
    ResearchLaboratories: 44,
    AnimalResearch: 45,
    InternationalResearchInstitutionsMIB: 46,
    SearchingForThoseInfectedVoluntarily: 47,
    HumanStudies: 48,
    SearchForDrugsForImmunity: 49,
    SearchingForAntibiotics: 50,
    VaccineSearch: 51,
    RecommendationsNotToLeaveTheHouse: 52,
    ForcedQuarantineForVisitors: 53,
    ClosingStores: 54,
    ProhibitionOfLeavingMinorsFromHomes: 55,
    Curfew: 56,
    IsolationOfInfectedPeople: 57,
    ProtectionOfHighRankingPersons: 58,
    ForcedTesting: 59,
    PolicePatrols: 60,
    MilitaryPatrols: 61,
    ClosingCities: 62,
    UtilizationOfClothesAndObjectsInContactWithInfected: 63,
    ProductionOfDisinfectantLiquids: 64,
    ProductionOfRubberGloves: 65,
    ProductionOfCottonMasks: 66,
    ProductionOfTremometers: 67,
    ProductionOfMasksWithFilter: 68,
    ProductionOfProtectiveSuits: 69,
    AdditionalRecruitmentOfInternalMedicineDoctors: 70,
    AdditionalRecruitmentOfNurses: 71,
    ConstructionOfClinics: 72,
    BuildingHospitals: 73,
    AdditionalRecruitmentOfSpecialistDoctors: 74,
    AdditionalRecruitmentOfBiologists: 75,
    AdditionalRecruitmentOfScientists: 76,
    BuildingResearchLaboratories: 77,
    AdditionalRecruitmentForVoluntaryVirusInfection: 78,
    AdditionalRecruitmentOfPoliceOfficers: 79,
    AdditionalRecruitmentOfMilitaryServices: 80,
    Security: 81,
    HealthService: 82,
    Politics: 83,
    Research: 84,
    Quarantine: 85,
    Production: 86,
  });

  RawMaterialGroups = {
    1: [ RawMaterials.ResistanceToVirus, RawMaterials.EvolutionPoints ],
    2: [ RawMaterials.PaperTowels, RawMaterials.AntibacterialWipe, RawMaterials.DisinfectantLiquid, RawMaterials.RubberGloves, RawMaterials.TabletsForImmunity, RawMaterials.CottonMask, RawMaterials.CourierDeliveringFoodToHomes, RawMaterials.Thermometer, RawMaterials.Antipyretics, RawMaterials.MaskWithFilter, RawMaterials.OxygenBottle, RawMaterials.ProtectiveSuit ],
    3: [ RawMaterials.Volunteers, RawMaterials.MedicalUniversityStudents, RawMaterials.InternalMedicineDoctors, RawMaterials.Clinic, RawMaterials.FreePreliminaryTestsForSuspects, RawMaterials.DisinfectingRooms, RawMaterials.Ambulances, RawMaterials.Nurses, RawMaterials.Hospitals, RawMaterials.SanitaryInspections, RawMaterials.SpecialistDoctors, RawMaterials.SecondDegreeSpecialists ],
    4: [ RawMaterials.PromotingHygiene, RawMaterials.TemperatureMeasurementsAndPreliminaryInterview, RawMaterials.ForcedObservationOfSuspects, RawMaterials.IncreasedFlightControl, RawMaterials.IncreasedControlOfInternationalTransport, RawMaterials.EnhancedBorderControl, RawMaterials.RestrictingMassEvents, RawMaterials.RestrictingAccessToCulturalGoods, RawMaterials.IncreasedSecurityProceduresForSchools, RawMaterials.PromotionOfRemoteWork, RawMaterials.AdditionalVacationDays, RawMaterials.AllocationOfFoodAndSanitaryProducts, RawMaterials.PromotionOfCremationOfCorpses ],
    5: [ RawMaterials.Biologists, RawMaterials.CollectingSamples, RawMaterials.Scientists, RawMaterials.VirusTesting, RawMaterials.ResearchLaboratories, RawMaterials.AnimalResearch, RawMaterials.InternationalResearchInstitutionsMIB, RawMaterials.SearchingForThoseInfectedVoluntarily, RawMaterials.HumanStudies, RawMaterials.SearchForDrugsForImmunity, RawMaterials.SearchingForAntibiotics, RawMaterials.VaccineSearch ],
    6: [ RawMaterials.RecommendationsNotToLeaveTheHouse, RawMaterials.ForcedQuarantineForVisitors, RawMaterials.ClosingStores, RawMaterials.ProhibitionOfLeavingMinorsFromHomes, RawMaterials.Curfew, RawMaterials.IsolationOfInfectedPeople, RawMaterials.ProtectionOfHighRankingPersons, RawMaterials.ForcedTesting, RawMaterials.PolicePatrols, RawMaterials.MilitaryPatrols, RawMaterials.ClosingCities, RawMaterials.UtilizationOfClothesAndObjectsInContactWithInfected ],
    7: [ RawMaterials.ProductionOfDisinfectantLiquids, RawMaterials.ProductionOfRubberGloves, RawMaterials.ProductionOfCottonMasks, RawMaterials.ProductionOfTremometers, RawMaterials.ProductionOfMasksWithFilter, RawMaterials.ProductionOfProtectiveSuits, RawMaterials.AdditionalRecruitmentOfInternalMedicineDoctors, RawMaterials.AdditionalRecruitmentOfNurses, RawMaterials.ConstructionOfClinics, RawMaterials.BuildingHospitals, RawMaterials.AdditionalRecruitmentOfSpecialistDoctors, RawMaterials.AdditionalRecruitmentOfBiologists, RawMaterials.AdditionalRecruitmentOfScientists, RawMaterials.BuildingResearchLaboratories, RawMaterials.AdditionalRecruitmentForVoluntaryVirusInfection, RawMaterials.AdditionalRecruitmentOfPoliceOfficers, RawMaterials.AdditionalRecruitmentOfMilitaryServices ], 
  };

  module.exports = RawMaterials;