const Category = {
    None: 0,
    Security: 2,
    Currency: 1,
    HealthService: 3,
    Politics: 4,
    Production: 7,
    Quarantine: 6,
    Research: 5
};

Object.freeze(Category);

const RawMaterial = {
  None: 0,
  ResistanceToVirus: 1,
  EvolutionPoints: 2,
  PaperTowels: 3,
  AntibacterialWipe: 4,
  DisinfectantLiquid: 5,
  RubberGloves: 6,
  TabletsForImmunity: 7,
  CottonMask: 8,
  CourierDeliveringFoodToHomes: 9,
  Thermometer: 10,
  Antipyretics: 11,
  MaskWithFilter: 12,
  OxygenBottle: 13,
  ProtectiveSuit: 14,
  Volunteers: 15,
  MedicalUniversityStudents: 16,
  InternalMedicineDoctors: 17,
  Clinic: 18,
  FreePreliminaryTestsForSuspects: 19,
  DisinfectingRooms: 20,
  Ambulances: 21,
  Nurses: 22,
  Hospitals: 23,
  SanitaryInspections: 24,
  SpecialistDoctors: 25,
  SecondDegreeSpecialists: 26,
  PromotingHygiene: 27,
  TemperatureMeasurementsAndPreliminaryInterview: 28,
  ForcedObservationOfSuspects: 29,
  IncreasedFlightControl: 30,
  IncreasedControlOfInternationalTransport: 31,
  EnhancedBorderControl: 32,
  RestrictingMassEvents: 33,
  RestrictingAccessToCulturalGoods: 34,
  IncreasedSecurityProceduresForSchools: 35,
  PromotionOfRemoteWork: 36,
  AdditionalVacationDays: 37,
  AllocationOfFoodAndSanitaryProducts: 38,
  PromotionOfCremationOfCorpses: 39,
  Biologists: 40,
  CollectingSamples: 41,
  Scientists: 42,
  VirusTesting: 43,
  ResearchLaboratories: 44,
  AnimalResearch: 45,
  InternationalResearchInstitutionsMIB: 46,
  SearchingForThoseInfectedVoluntarily: 47,
  HumanStudies: 48,
  SearchForDrugsForImmunity: 49,
  SearchingForAntibiotics: 50,
  VaccineSearch: 51,
  RecommendationsNotToLeaveTheHouse: 52,
  ForcedQuarantineForVisitors: 53,
  ClosingStores: 54,
  ProhibitionOfLeavingMinorsFromHomes: 55,
  Curfew: 56,
  IsolationOfInfectedPeople: 57,
  ProtectionOfHighRankingPersons: 58,
  ForcedTesting: 59,
  PolicePatrols: 60,
  MilitaryPatrols: 61,
  ClosingCities: 62,
  UtilizationOfClothesAndObjectsInContactWithInfected: 63,
  ProductionOfDisinfectantLiquids: 64,
  ProductionOfRubberGloves: 65,
  ProductionOfCottonMasks: 66,
  ProductionOfTremometers: 67,
  ProductionOfMasksWithFilter: 68,
  ProductionOfProtectiveSuits: 69,
  AdditionalRecruitmentOfInternalMedicineDoctors: 70,
  AdditionalRecruitmentOfNurses: 71,
  ConstructionOfClinics: 72,
  BuildingHospitals: 73,
  AdditionalRecruitmentOfSpecialistDoctors: 74,
  AdditionalRecruitmentOfBiologists: 75,
  AdditionalRecruitmentOfScientists: 76,
  BuildingResearchLaboratories: 77,
  AdditionalRecruitmentForVoluntaryVirusInfection: 78,
  AdditionalRecruitmentOfPoliceOfficers: 79,
  AdditionalRecruitmentOfMilitaryServices: 80,
  Security: 81,
  HealthService: 82,
  Politics: 83,
  Research: 84,
  Quarantine: 85,
  Production: 86,
};

Object.freeze(RawMaterial);

const UpgradeType = {
    ShorteningTime: 0,
    MultiplyingProduction: 1
};

Object.freeze(UpgradeType);